### ISSUE TITLE
Buildproblem

### ISSUE THREAD

**Issue by Harald-B-Rupp** [BioID-GmbH/BWSClient-WebApp#1]
Dear BioID Team,

I try to build the BWSClient-WebApp using

dotnet build  -configuration Release x64 --self-contained true 

but I get error MSB1001: Unknown switch

I use .Net8 and Visual Studio Code (latest version)

Thanks for an advice

dotnet build  -configuration Release <target platform> --self-contained true

**Comment by mebealex** [comment]
Hello Harald-B-Rupp,

Please use '--configuration Release' or '-c Release' for configuration parameters. 
We have corrected the typo in the description.

dotnet build --configuration Release --self-contained true
or
dotnet build -c Release --self-contained true

If you still have problems, we are happy to help.
BioID Team

**Comment by Harald-B-Rupp** [comment]
Dear BioID Team,
thanks for the support, I will close the Issue
Best Regards Harald
